input_file: "86_12.amc.4d"
init_n_rgm: 4
noise_scale: 0
h: 4
window: 10
svd_threshold: 0.995
init_window: 120
step: 1
switch_cost: 12
estimate_cost: 12
max_iter: 10
lcurr: 10
lstep: 30
lrprt: 6
train_size: 5500
